alpha-asp/Alpha

README.md
all directory paths end with slashes, except that one.
=> Make directory paths consistent in README.md

.gitattributes, .gitignore, AUTHORS, CONTRIBUTORS, src/main/java/at/ac/tuwien/kr/alpha/common/NoGood.java, src/main/java/at/ac/tuwien/kr/alpha/solver/Assignment.java, src/main/java/at/ac/tuwien/kr/alpha/solver/ChoiceStack.java, src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/NaiveSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMin.java, src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BranchingHeuristic.java, src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMinTest.java
To implement a berkmin-like heuristics for a lazy-grounding ASP solver, an interface BranchingHeuristic has been created which is implemented by BerkMin.
The following changes to DefaultSolver have been made:
- When a NoGood is violated, it is reported to the branching heuristic.
- When a new NoGood is obtained from the grounder, it is reported to the branching heuristic.
- When a choice has to be made, the branching heuristic is employed to choose atom and sign (polarity).
- Because the sign chosen first is not always true anymore, a backtrack does not always choose false anymore but goes into the branch that has not yet been explored.
- If the branching heuristic cannot make a choice, we fall back to the old method to compute a choice.
=> Initial version of BerkMin-like heuristics

src/main/java/at/ac/tuwien/kr/alpha/grounder/AtomStore.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/bridges/HexBridge.java
Predicate names can be arbitrarily chosen by the grounder, use the `internal` flag instead.
If I did not mess up, this should work and be more portable (independent of grounder implementation).
=> Check for internal atoms using flag not predicate name

src/main/java/at/ac/tuwien/kr/alpha/Util.java
Removing unused util method (only usage was removed in 3e591db9c121d7ebd38055c92af4f43aaa79c50d because the same result can be achieved by Collections.singleton).
=> Removing unused method

src/main/java/at/ac/tuwien/kr/alpha/grounder/BridgedGrounder.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/bridges/Bridge.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/bridges/HexBridge.java, src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
I've adapted the `HexBridge` such that the nogoods imported from Hex are not added directly anymore, but are transformed into nogoods representing the corresponding rules in Alpha. First, I had added a second method to the `Bridge` interface for importing new ground rules. Now, the transformation is made directly inside `getNoGoods`, so that only minimal changes are required in the other classes. Only `RULE_BODIES_PREDICATE` in `NaiveGrounder` has to be _public_ and additional arguments need to be passed to `getNoGoods` for generating new choice atoms. So, I think the new version is better; the the previous one is contained in 111d9f5.
=> Alphahex rule import

src/main/java/at/ac/tuwien/kr/alpha/CustomErrorListener.java, src/main/java/at/ac/tuwien/kr/alpha/Main.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/parser/ParsedProgram.java, src/test/java/at/ac/tuwien/kr/alpha/MainTest.java, src/test/java/at/ac/tuwien/kr/alpha/antlr/ParserTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/PigeonHoleTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/SolverTests.java
This is a quick solution to #31 
In principle it does what it needs to do. What we will need in the future is referencing the file name in case of parsing errors. Currently files are concatenated and the line numbers that ANTLR error messages refer to are probably not consistent with file numbers of actual files.
So I'd say it's a step in the right direction, but we'll need to follow up on the issue.
=> Accept multiple input files

.travis.yml
For some unknown reason, Travis CI kills the build while running all tests. Enabling sudo seems to avoid this issue.
=> Moving to sudo-enabled Travis CI (to avoid test failure).

src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java, src/test/java/at/ac/tuwien/kr/alpha/solver/ChoiceManagerTests.java, src/test/java/at/ac/tuwien/kr/alpha/solver/HanoiTowerTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/OmigaBenchmarksTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/PartSubpartConfigurationTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/PigeonHoleTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/RacksTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/SolverTests.java, src/test/java/at/ac/tuwien/kr/alpha/solver/ThreeColouringRandomGraphTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/ThreeColouringTestWithRandom.java, src/test/java/at/ac/tuwien/kr/alpha/solver/ThreeColouringWheelTest.java
Do not test so many configurations by default, just one. Allow setting configurations to be tested via properties.
This also allows for testing multiple grounder implementations.
=> Restructure AbstractSolverTests

README.md
Current Coveralls badge is taken from old `ci` branch, not `master`.
=> Showing coverage badge for master branch.

README.md
README.md already has a section on suggested reading, but this did not include any research papers on Alpha itself. I propose to change this situation.
=> Mention research papers on Alpha in README.md

src/main/java/at/ac/tuwien/kr/alpha/Alpha.java, src/main/java/at/ac/tuwien/kr/alpha/common/Predicate.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ComparisonAtom.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ExternalAtom.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/FixedInterpretationLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/BinaryPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/BindingMethodPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/BindingPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/IntPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/LongPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/MethodPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/NonBindingPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/PredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/SuppliedPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/UnaryPredicateInterpretation.java, src/main/java/at/ac/tuwien/kr/alpha/common/terms/ConstantTerm.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/NoGoodGenerator.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/atoms/IntervalAtom.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/parser/ParseTreeVisitor.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/parser/ProgramParser.java, src/test/java/at/ac/tuwien/kr/alpha/AlphaTest.java
Renaming package `common.interpretations` to `common.fixedinterpretations` and the interface `InterpretableLiteral` to `FixedInterpretationLiteral`.
=> Renaming interpretations to fixed interpretations.

src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/SolverMaintainingStatistics.java, src/test/java/at/ac/tuwien/kr/alpha/solver/SolverStatisticsTests.java
i.e. the number of times the solver had to backtrack after closing unassigned atoms.
Contributes to #113
=> Statistics: Print number of conflicts after closing

src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/DependencyDrivenHeuristic.java, src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/AlphaHeuristicTestAssumptions.java
Please reactivate `AlphaHeuristicTestAssumptions`, a set of test cases deactivated by 486ffdb1f4379d9bccf2dcedafa322d7175db062. These test cases are important for domain-independent heuristics to work correctly. For example, the test cases would have been able to detect a bug introduced by 211641771b0f24ac4725eed0ca9e3bd4a0355b71 and fixed by 2a2cb1cc68c72e736851543a774e33ea3f87f2f9 if they would have been enabled. The idea is to adapt the test cases (and the heuristics, if necessary) when something in the generation of nogoods changes.
=> Reactivate AlphaHeuristicTestAssumptions and fix bug in DependencyDrivenHeuristic

src/main/java/at/ac/tuwien/kr/alpha/common/atoms/Atom.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/BasicAtom.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/BasicLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ComparisonAtom.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ComparisonLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ExternalAtom.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ExternalLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/FixedInterpretationLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/Literal.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/IndexedInstanceStorage.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/WorkingMemory.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/atoms/IntervalAtom.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/atoms/IntervalLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/atoms/RuleAtom.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/parser/ParseTreeVisitor.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/transformation/ChoiceHeadToNormal.java, src/test/java/at/ac/tuwien/kr/alpha/AlphaTest.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/IndexedInstanceStorageTest.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/SubstitutionTest.java
Globally replace `Literal.negated` by `Literal.positive` for clarity (e.g., it is more intuitive if `atom.toLiteral(true)` creates a positive literal than a negative one).
=> Invert handling of literal polarity

src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
Solves part of #113:
E.g. message
>Overall performance: 733 decision in 8003s or 91.59065 decisions per sec. Overall replayed assignments: 152. 
is now 
>Overall performance: 733 decisions in 8.003s or 91.59065 decisions per sec. Overall replayed assignments: 152.
=> Fix error in performance output messages.

src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/PerformanceLog.java
Performance logs (e.g. "Overall performance: 6350 decisions in 27.02s or 235.0111 decisions per sec. Overall replayed assignments: 0") now continue counting when an answer set is found, i.e. they measure performance across the whole solving process.
Fixes #166
=> Fix error in performance logs

src/main/java/at/ac/tuwien/kr/alpha/solver/ChoiceManager.java
Before this fix, the decision level was printed before it was increased, thus connecting the chosen atom with a wrong decision level in the log output.
=> Fix log message in ChoiceManager.choose

.appveyor.yml, .travis.yml, build.gradle
See https://scans.gradle.com/
With this addition we will have the possibility to access and share detailed information about the build process of Alpha, such as duration of build phases, an overview of dependencies, etc. To get an idea, check out a build scan from this PR's source branch: https://scans.gradle.com/s/j7kqgasr5a7am
=> Enable Gradle Build Scans

src/main/java/at/ac/tuwien/kr/alpha/Alpha.java, src/main/java/at/ac/tuwien/kr/alpha/Main.java, src/main/java/at/ac/tuwien/kr/alpha/config/CommandLineParser.java, src/main/java/at/ac/tuwien/kr/alpha/config/InputConfig.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/GrounderFactory.java, src/test/java/at/ac/tuwien/kr/alpha/AlphaTest.java, src/test/java/at/ac/tuwien/kr/alpha/MainTest.java
- overloaded ```solve(..)``` and ```prepareSolverFor(..)``` in ```Alpha.java``` with optional filter parameter
- calling ```prepareSolverFor``` with filter got from ```InputConfig``` in ```Main```
- overloaded "simple version" of ```getInstance``` in ```GrounderFactory``` with optional filter parameter
- added test cases (in ```MainTest``` and ```AlphaTest```)
=> fixed broken filter option (issue #189)

src/main/java/at/ac/tuwien/kr/alpha/Alpha.java, src/main/java/at/ac/tuwien/kr/alpha/config/CommandLineParser.java, src/main/java/at/ac/tuwien/kr/alpha/config/SystemConfig.java, src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/SolverFactory.java, src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java
Add-on to #197, introducing a CLI option to disable nogood forgetting. This will mainly be useful for experiments.
I´ve also refactored the solver constructor  to accept a large `SystemConfig` object instead of many small configuration parameters, because otherwise the constructor's signature would grow ever larger over time.
=> CLI option to disable nogood forgetting

src/main/java/at/ac/tuwien/kr/alpha/common/AtomStore.java, src/main/java/at/ac/tuwien/kr/alpha/common/AtomStoreImpl.java, src/main/java/at/ac/tuwien/kr/alpha/solver/AtomCounter.java, src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java, src/test/java/at/ac/tuwien/kr/alpha/solver/AtomCounterTests.java
Adds the capability to count atoms (grouped by classes implementing `Atom`). The numbers are currently printed only in debug log messages, similarly as numbers of nogoods in 84d86b3437841cc2007bd09863e3aaa4bc3d8dac. In the future, all this information shall be included in the statistics (cf. #113).
=> Add capability to count atoms for statistics

src/main/resources/logback.xml, src/test/resources/logback.xml
Use separate logback.xmls for testing and jar file:
* src/main/resources/logback.xml: Used in jar file (both bundledJar and normal "slim" jar), only logging to stdout, level = INFO
* src/test/resources/logback.xml: Used for unit tests, logging to stdout and junit.log, level = DEBUG
Addresses issue #204
=> separate logback configs for tests and bundled jar

build.gradle
Addresses issue #214 
* changed deprecated dependency config "compile" to "implementation"
* changed deprecated property "archiveName" to use "archiveFileName" for bundledJar task
* exclude all "LICENSE.txt" and "NOTICE.txt" files from bundled jar
Note that LICENSE and NOTICE files are excluded from bundled jar in order to avoid having to handle duplicate files since all apache commons dependencies have their own files of that name which would have to be properly handled (ideally merged) otherwise. The aforementioned "proper handling" would require use of the gradle shadow plugin, which unfortunately is not gradle 7 compliant itself (as of version 5.2.0)
=> Fix deprecation warnings for gradle 7

build.gradle, src/main/java/at/ac/tuwien/kr/alpha/AnswerSetToXlsxWriter.java, src/main/java/at/ac/tuwien/kr/alpha/Main.java, src/main/java/at/ac/tuwien/kr/alpha/api/Alpha.java, src/main/java/at/ac/tuwien/kr/alpha/api/mapper/AnswerSetToObjectMapper.java, src/main/java/at/ac/tuwien/kr/alpha/api/mapper/impl/AnswerSetToWorkbookMapper.java, src/main/java/at/ac/tuwien/kr/alpha/config/CommandLineParser.java, src/main/java/at/ac/tuwien/kr/alpha/config/InputConfig.java, src/test/java/at/ac/tuwien/kr/alpha/AlphaTest.java, src/test/java/at/ac/tuwien/kr/alpha/AnswerSetToXlsxWriterTest.java, src/test/java/at/ac/tuwien/kr/alpha/api/AlphaTest.java, src/test/java/at/ac/tuwien/kr/alpha/api/mapper/impl/AnswerSetToWorkbookMapperTest.java
In order to aid data exploration and visualization, this PR introduces a new feature, allowing answer sets to be written as xlsx files rather than just printed to stdout.
* new package `at.ac.tuwien.kr.alpha.api` as top-level package for public API types (such as `Alpha.java`)
* Interface `AnswerSetToObjectMapper<T>` defining a mapping function from `AnswerSet` to a type parameter `T`
* Mapper implementation to map from `AnswerSet` to `Workbook`, i.e. xlsx workbooks. Implementation is realized using [Apache POI](https://poi.apache.org/) using the approach outlined [here](https://www.callicoder.com/java-write-excel-file-apache-poi/)
* New argument `-wx <path>`: When set,  answer sets will be written to xlsx files at the given path, e.g. the call `java -jar alpha.jar -i prog.asp -wx …
=> Feature: Render answer sets as excel workbooks (xlsx files)

src/main/java/at/ac/tuwien/kr/alpha/api/externals/stdlib/AspStandardLibrary.java, src/test/java/at/ac/tuwien/kr/alpha/api/externals/stdlib/AspStandardLibraryTest.java
The mentioned comparisons are needed to be able to chronologically rank atoms based on datetimes (possibly containing duplicates, i.e. equal timestamps) in ASP.
Added methods:
* `AspStandardLibrary#datetimeIsEqual`
* `AspStandardLibrary#datetimeIsBeforeOrEqual`
=> add EQ ("==") and LEQ  ("<=") comparisons for datetimes to standard library

src/main/java/at/ac/tuwien/kr/alpha/common/Assignment.java, src/main/java/at/ac/tuwien/kr/alpha/common/IntIterator.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/Grounder.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java, src/main/java/at/ac/tuwien/kr/alpha/solver/ChoiceInfluenceManager.java, src/main/java/at/ac/tuwien/kr/alpha/solver/ChoiceManager.java, src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/NaiveSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/NoGoodStoreAlphaRoaming.java, src/main/java/at/ac/tuwien/kr/alpha/solver/ShallowAntecedent.java, src/main/java/at/ac/tuwien/kr/alpha/solver/TrailAssignment.java, src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/HeapOfActiveAtoms.java, src/main/java/at/ac/tuwien/kr/alpha/solver/learning/GroundConflictNoGoodLearner.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/ChoiceGrounder.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/DummyGrounder.java, src/test/java/at/ac/tuwien/kr/alpha/solver/TrailAssignmentTest.java, src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/AlphaHeuristicTestAssumptions.java
Alpha currently creates a lot of temporary `Integer` objects, most of it by autoboxing. This PR significantly reduces the amount of those (on some instance from 144 million down to 4 million temporary `Integer` objects).
The changes are as follows:
- Introduction of `IntIterator` instead of `Iterator<Integer>`.
- `TrailAssignment` stores the trail as `int[]` instead of `ArrayList<Integer>`.
- Logger calls that print `int` (which get autoboxed to `Integer`) moved inside corresponding if-statements.
- Additionally avoid creation of never-needed `BinaryAntecedent` by lazily postponing their instantiation, using a long-living object as placeholder (i.e., `ShallowAntecedent`).
=> Avoiding Integer objects.

src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BranchingHeuristicFactory.java, src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java
Deprecate old domain-independent heuristics, and run solver tests only for non-deprecated heuristics.
The reason is that these old heuristics have not been maintained for a while and often perform poorly (#181). Sometimes they make CI break because tests take too much time using those heuristics.
=> Deprecate old domain-independent heuristics

src/main/java/at/ac/tuwien/kr/alpha/common/terms/ConstantTerm.java, src/test/java/at/ac/tuwien/kr/alpha/common/TermTest.java
Fixes the bug described in issue #244
* Extended `ConstantTerm#equals` to check whether `this.symbolic != other.symbolic`
* Extended `ConstantTerm#compareTo` to compare based on priority if `this.symbolic != other.symbolic`
* additional Test Case in `TermTest` checking the condition from issue #244
=> Bugfix: String-typed ConstantTerms for strings and constant symbols mistakenly equal (Issue #244)

src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java, src/test/java/at/ac/tuwien/kr/alpha/common/SubstitutionTest.java, src/test/java/at/ac/tuwien/kr/alpha/common/SubstitutionTestUtil.java, src/test/java/at/ac/tuwien/kr/alpha/common/UnifierTest.java
Move `SubstitutionTest` and `UnifierTest` to `common` package because `Substitution` and `Unifier` are also in `common` package. Move also two static methods from `NaiveGrounder` to a new class `SubstitutionTestUtil` because those methods are only used by tests.
=> Move substitution test

src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ComparisonLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ExternalLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/common/atoms/FixedInterpretationLiteral.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/atoms/IntervalLiteral.java, src/test/java/at/ac/tuwien/kr/alpha/api/externals/stdlib/AspStandardLibraryTest.java, src/test/java/at/ac/tuwien/kr/alpha/common/fixedinterpretations/FixedInterpretationLiteralsTest.java
Fixes the issue described in #234.
For external atoms that have outputs, if the literal is negated, the truth value of the literal is determined as follows:
```The (negated external) literal lit is true iff no list of terms TL exists in the external atom's output, such that the terms in TL equal the substituted values of the literal's output variables (i.e. the values those variables are bound to by the grounder)```
Also, `FixedInterpretationLiteral#getSubstitutions` renamed to `getSatisfyingSubstitutions` to properly represent method semantics in the method name.
=> Fix evaluation of negated external atoms (Issue #234)

src/main/java/at/ac/tuwien/kr/alpha/solver/TrailAssignment.java, src/main/java/at/ac/tuwien/kr/alpha/solver/learning/GroundConflictNoGoodLearner.java, src/test/java/at/ac/tuwien/kr/alpha/solver/SolverTests.java
Fix bug in computation of backjumping level for violated unary nogoods in GroundConflictNoGoodLearner and related issue with erroneous storage
of conflicting out-of-order assignments in TrailAssignment. Fixes #239.
=> Fix issue #239

src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
=> Improve code quality of DefaultSolver a bit.

src/main/java/at/ac/tuwien/kr/alpha/grounder/Substitution.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/parser/ProgramPartParser.java, src/test/java/at/ac/tuwien/kr/alpha/TestUtil.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounderTest.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/RuleGroundingOrderTest.java
Some unit tests already have been adapted to use the new parser for `Literal`s instead of using various constructors, which makes the unit tests easier to understand.
=> Introduce ProgramPartParser to simplify construction of parts of programs

src/main/java/at/ac/tuwien/kr/alpha/grounder/Unifier.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/structure/AnalyzeUnjustified.java
Justification analysis used erroneously specific atom to test whether a given substitution is excluded by a more general one. Now a more general atom is constructed for the test. This fixes issue #211, this fix/PR is independent of the phase saving and restarts branch as the bug was just unearthed there but is present in master, too.
=> Fix bug in justification analysis, address issue #211.

build.gradle, src/main/java/at/ac/tuwien/kr/alpha/Main.java, src/main/java/at/ac/tuwien/kr/alpha/common/BasicAnswerSetFormatter.java, src/main/java/at/ac/tuwien/kr/alpha/common/SimpleAnswerSetFormatter.java, src/main/java/at/ac/tuwien/kr/alpha/config/CommandLineParser.java, src/main/java/at/ac/tuwien/kr/alpha/config/SystemConfig.java, src/test/java/at/ac/tuwien/kr/alpha/common/AnswerSetFormatterTest.java, src/test/java/at/ac/tuwien/kr/alpha/config/CommandLineParserTest.java
Adds a new command line parameter (`sep <separator>`) in order to influence the way answer sets are printed to `stdout`.
Example:
```
$ java -jar Alpha-bundled.jar -str "a. b(c). d(e, f)." -sep ",\n"
```
formats the answer set as:
```
{ a,
b(c),
d(e, f) }
```
=> Command Line Interface - Make separator string for atoms within printed answer set configurable

src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/Substitution.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/instantiation/AbstractLiteralInstantiationStrategy.java, src/main/java/at/ac/tuwien/kr/alpha/grounder/transformation/StratifiedEvaluation.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounderTest.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/NoGoodGeneratorTest.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/SubstitutionTest.java, src/test/java/at/ac/tuwien/kr/alpha/grounder/UnifierTest.java
Removes the need for upfront cloning of Substitutions when checking unification.
=> Substitution lazy cloning

src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java, src/test/java/at/ac/tuwien/kr/alpha/solver/AggregatesTest.java
Adds a new JUnit parameter to `AbstractSolverTests`: `evaluateStratifiedPart` determines whether the `evaluateStratifiedPart` flag in the `SystemConfig` returned by `AbstractSolverTests#buildSystemConfig` is `true` or `false`.
All tests extending `AbstractSolverTests` are therefore run once with and once without stratified evaluation enabled.
Since this only adds about 500 additional test cases to a normal build, I decided to run both variants in every build, not just CI builds.
Closes #275
=> Ensure regression test cases are run with and without StratifiedEvaluation enabled

src/main/java/at/ac/tuwien/kr/alpha/grounder/Unifier.java
javadoc doesn't like `>` symbols. One way to solve this is to wrap them
`@literal`
#193
=> Fix javadoc error in Unifier

src/main/java/at/ac/tuwien/kr/alpha/api/query/AnswerSetQuery.java, src/main/java/at/ac/tuwien/kr/alpha/common/AnswerSet.java, src/main/java/at/ac/tuwien/kr/alpha/common/terms/ConstantTerm.java, src/test/java/at/ac/tuwien/kr/alpha/api/query/AnswerSetQueryTest.java
This PR adds a new class `AnswerSetQuery` that allows API users to process answer sets with a bit less boilerplate code.
Answer set queries can be used via the new `AnswerSet#query` method that accepts an `AnswerSetQuery` as its argument.
For an intuition on how to use answer set queries, see below examples:
```
Answer Set {
p(a),
p("a"),
p(b)
p(1),
p(2),
p(3),
p(4),
p(5),
q(a),
q(b),
r(x, f(x)),
r(x, f(y)),
r(y, f(x)),
r(x, y)
}
Some queries:
List<Atom> queryResult = answerSet.query(AnswerSetQuery.forPredicate(Predicate.getInstance("p", 1)));
// queryResult contains all instances of p/1
List<Atom> queryResult = answerSet.query(
AnswerSetQuery.forPredicate(Predicate.getInstance("p", 1))
.withConstantEquals(0, "a");
// queryResult contains p(a), but not p("a") which is a string rather than …
```
=> AnswerSetQuery: API feature to query answer sets in a fluent way

src/main/java/at/ac/tuwien/kr/alpha/common/Assignment.java, src/main/java/at/ac/tuwien/kr/alpha/solver/Choice.java, src/main/java/at/ac/tuwien/kr/alpha/solver/ChoiceManager.java, src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/NaiveSolver.java, src/main/java/at/ac/tuwien/kr/alpha/solver/PerformanceLog.java, src/main/java/at/ac/tuwien/kr/alpha/solver/TrailAssignment.java, src/main/java/at/ac/tuwien/kr/alpha/solver/WritableAssignment.java
Some refactoring/polishing inside the solver component, mostly DefaultSolver. Changes are intended to support subclassing of DefaultSolver for optimization tasks/weak constraints.
=> Refactor DefaultSolver

.github/workflows/build.yml
Improvements to our GitHub Actions configuration:
Checks that the file at `/gradle/wrapper/gradle-wrapper.jar` is known (on some allowlist). Raises the bar for someone to push a malicious JAR file to this repo.
Is a platform-independent way to invoke Gradle, and automatically handles caching. This way we don't have to provide different ways to invoke Gradle based on `matrix.os`.
=> ci: Clean up GitHub Actions spec

CITATION.cff, RELEASE.md
For more context, refer to:
* [citation-file-format.github.io](https://citation-file-format.github.io/)
* [Supported by GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
* [Supported by Zenodo](https://twitter.com/ZENODO_ORG/status/1420357001490706442)
* [Supported by Zotero](https://twitter.com/zotero/status/1420515377390530560)
The file should not see many changes (just like `AUTHORS` and `CONTRIBUTORS`). The [spec is quite broad and flexible](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md), so we could encode *much* more, but I'd prefer to start with something simple.
Opinions?
=> Add `CITATION.cff`

alpha-cli-app/build.gradle.kts
[CVE-2021-44228](https://nvd.nist.gov/vuln/detail/CVE-2021-44228) is making news. AFAIK Alpha is not vulnerable, and, as a CLI application, also not really a target, but let's update Log4j anyway.
=> cli: Upgrade Log4j

alpha-core/src/main/java/at/ac/tuwien/kr/alpha/core/programs/transformation/aggregates/AggregateOperatorNormalization.java, alpha-core/src/test/java/at/ac/tuwien/kr/alpha/core/programs/transformation/aggregates/AggregateOperatorNormalizationTest.java, alpha-core/src/test/java/at/ac/tuwien/kr/alpha/core/solver/AggregatesTest.java
Fixed in `AggregateOperatorNormalization`:
Aggregates of form `#aggr{...} OP TERM` are rewritten into `TERM inv(OP) #aggr{...}` and then processed as before.
`inv(OP)` refers to the inverse operator, i.e. `inv(<) = >=` etc. For operators `=` and `!=` no inverse operator is used, i.e. rewritten form is `TERM OP #aggr{...}`.
Closes #311
=> Fix handling of aggregate literals with only a right-hand comparison term (Issue #311)

gradle.properties
In preparation for the actual release of version 0.6.0, we need to set the correct version in gradle.properties before we can create the tag
=> release preparation: set version to 0.6.0

gradle.properties
Tag for release v0.6.0 has been created, now set the version in `master` to 0.7.0-SNAPSHOT
=> bump version to 0.7.0-SNAPSHOT

.gitattributes
This is a leftover from PR #274: The path `benchmarks/**`, containing an enormous amount of ASP sources, should be marked as vendored, i.e. excluded from github statistics. Since the folder in question got moved into `alpha-core`, we need to adapt the config in `.gitattributes` accordingly.
=> core: fix vendored path config for benchmark files

.github/workflows/build.yml
To work around deprecation of `set-output`, see also https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: Upgrade actions/setup-java

.github/workflows/build.yml, build.gradle.kts
Refactoring Alpha into modules resulted in coverage to be computed only individually for each module. This results in many lines of code being considered not hit by any test, while they indeed are tested in (functional-/integration-)tests of another module. This PR tries to rectify coverage computation by using Jacoco's aggregate plugin on the top-level of the build.
=> Add Jacoco aggregation for coverage.

buildSrc/src/main/kotlin/alpha.java-common-conventions.gradle.kts
- Fixes #362 
- Make dependency on commons-compress explicit to pull-in newer version.
- Make dependency on Guava explicit as it no longer is transitively included.
=> Update dependencies to avoid several CVEs.
