.gitattributes
.gitignore
AUTHORS
CONTRIBUTORS

Before changes by Siemens will be integrated, company and authors shall be mentioned in AUTHORS and CONTRIBUTORS. Also, some changes to .gitattributes and .gitignore are made to fit development environments of new developers.

Preparing repository for contributions by Siemens

---

src/main/java/at/ac/tuwien/kr/alpha/Util.java
src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
src/main/java/at/ac/tuwien/kr/alpha/solver/GroundConflictNoGoodLearner.java
src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMin.java
src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BranchingHeuristic.java
src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMinTest.java

Improvement to BerkMin: Now counting literals in nogoods responsible for the conflict.

Berkmin counting literals in nogoods responsible for the conflict

---

src/main/java/at/ac/tuwien/kr/alpha/grounder/AtomId.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java
src/main/java/at/ac/tuwien/kr/alpha/solver/BasicAssignment.java
src/main/java/at/ac/tuwien/kr/alpha/solver/BasicNoGoodStore.java
src/main/java/at/ac/tuwien/kr/alpha/solver/GroundConflictNoGoodLearner.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/ChoiceGrounder.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounderTest.java

Various minor changes (bug fix, performance improvement, toString() implementation).

Various minor changes

---

src/main/java/at/ac/tuwien/kr/alpha/grounder/AtomId.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java
src/main/java/at/ac/tuwien/kr/alpha/solver/BasicAssignment.java
src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMin.java
src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/NaiveHeuristic.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounderTest.java
src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMinTest.java

- ignore atoms that are no choice points
- bugfixes

Improvements to BerkMin

---

src/main/java/at/ac/tuwien/kr/alpha/Main.java
src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
src/main/java/at/ac/tuwien/kr/alpha/solver/SolverFactory.java
src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMin.java
src/test/java/at/ac/tuwien/kr/alpha/solver/DeterministicDefaultSolverTest.java
src/test/java/at/ac/tuwien/kr/alpha/solver/RandomizedDefaultSolverTest.java
src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMinTest.java

This addresses the discussion in #18 
* Single source of randomness, trickles down from `Main`
* Deterministic and random tests for `DefaultSolver`

Get randomness back under control

---

src/main/java/at/ac/tuwien/kr/alpha/Main.java
src/main/java/at/ac/tuwien/kr/alpha/solver/ChoiceManager.java
src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMin.java
src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/BranchingHeuristicFactory.java
src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java
src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMinTest.java

- BerkMin now uses ChoiceManager (as NaiveHeuristic)
- DefaultSolver's branching heuristic can be chosen via a factory
- AbstractSolverTests use this to run test cases with several heuristics

Configurable branching heuristics

---

src/main/java/at/ac/tuwien/kr/alpha/solver/BasicAssignment.java

Since logging is very expensive already and a large proportion of log messages come from this statement, I propose changing its level from DEBUG to TRACE.

Making BasicAssignment logging less verbose.

---

src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java

Include numbers of backtracks and backjumps in DefaultSolver log

---

src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
src/main/java/at/ac/tuwien/kr/alpha/solver/SolverCounters.java

Follow-up to #52 fixing CodeBeat issue

Extract counter variables from DefaultSolver

---

src/main/java/at/ac/tuwien/kr/alpha/common/BasicAtom.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/AtomStore.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/BooleanAssignmentReader.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/Grounder.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java
src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
src/main/java/at/ac/tuwien/kr/alpha/solver/NaiveSolver.java
src/test/java/at/ac/tuwien/kr/alpha/common/NoGoodTest.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/ChoiceGrounder.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/DummyGrounder.java
src/test/java/at/ac/tuwien/kr/alpha/solver/ChoiceManagerTests.java
src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/AlphaHeuristicTestAssumptions.java

Changes the grounder to only create ground instances of rules/constraints whose positive body is currently satisfied.

Selective grounding

---

src/main/antlr/at/ac/tuwien/kr/alpha/antlr/ASPCore2.g4
src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ExternalAtom.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java
src/test/java/at/ac/tuwien/kr/alpha/AlphaTest.java

Fix external atom variable bindings

---

src/main/java/at/ac/tuwien/kr/alpha/Alpha.java
src/main/java/at/ac/tuwien/kr/alpha/common/predicates/ExternalSupplier.java
src/main/java/at/ac/tuwien/kr/alpha/common/predicates/FixedInterpretationPredicate.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java
src/test/java/at/ac/tuwien/kr/alpha/AlphaTest.java

Allow suppliers backing external atoms

---

src/main/java/at/ac/tuwien/kr/alpha/Main.java
src/main/java/at/ac/tuwien/kr/alpha/common/Rule.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/AtomStore.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/NonGroundRule.java
src/test/java/at/ac/tuwien/kr/alpha/MainTest.java
src/test/java/at/ac/tuwien/kr/alpha/antlr/ParserTest.java

Replace "\n" by System.lineSeparator(), and fix some typos

---

src/main/java/at/ac/tuwien/kr/alpha/common/Rule.java
src/test/java/at/ac/tuwien/kr/alpha/common/ProgramTest.java

Implement toString() in Program

---

src/main/java/at/ac/tuwien/kr/alpha/solver/NoGoodStoreAlphaRoaming.java
src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java
src/test/java/at/ac/tuwien/kr/alpha/solver/HeadBodyTransformationTests.java
src/test/java/at/ac/tuwien/kr/alpha/solver/NoGoodStoreAlphaRoamingTest.java
src/test/java/at/ac/tuwien/kr/alpha/solver/SolverTests.java

Fix watches in case of conflict by assignments at lower decision level.

---

src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java

test: All solvers and stores on CI

---

src/main/antlr/at/ac/tuwien/kr/alpha/antlr/ASPCore2.g4
src/main/java/at/ac/tuwien/kr/alpha/grounder/parser/ProgramParser.java
src/test/java/at/ac/tuwien/kr/alpha/antlr/ParserTest.java

Force ANTLR to parse full input and abort on syntax error.

---

src/main/java/at/ac/tuwien/kr/alpha/grounder/NonGroundRule.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/RuleToStringTest.java

Fix error in NonGroundRule.toString()

---

src/main/java/at/ac/tuwien/kr/alpha/Main.java
src/main/java/at/ac/tuwien/kr/alpha/solver/ChoiceManager.java
src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
src/main/java/at/ac/tuwien/kr/alpha/solver/SolverMaintainingStatistics.java
src/test/java/at/ac/tuwien/kr/alpha/MainTest.java
src/test/java/at/ac/tuwien/kr/alpha/solver/SolverStatisticsTests.java

Fixed issues:
- #99 Print statistics to stdout if stats option is present on command line
- #102 Too many backtracks counted in solver statistics

Solver statistics

---

src/test/java/at/ac/tuwien/kr/alpha/AlphaTest.java

- Split unit test `problematicRuns` to ease problem localisation
- Introduce assertion to unit test `smallGraph`

Small improvements to AlphaTest

---

src/main/java/at/ac/tuwien/kr/alpha/solver/ChoiceManager.java

Fix: Avoid duplicate work in ChoicePoint.recomputeActive

---

src/test/java/at/ac/tuwien/kr/alpha/solver/NoGoodStoreAlphaRoamingTest.java
src/test/java/at/ac/tuwien/kr/alpha/solver/heuristics/BerkMinTest.java

Fix usage of AtomStoreTest#fillAtomStore

---

src/main/java/at/ac/tuwien/kr/alpha/common/terms/ArithmeticTerm.java
src/test/java/at/ac/tuwien/kr/alpha/common/terms/TestMinusTerm.java

Implement MinusTerm#normalizeVariables

---

src/main/java/at/ac/tuwien/kr/alpha/common/terms/ArithmeticTerm.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/NaiveGrounder.java
src/test/java/at/ac/tuwien/kr/alpha/common/terms/TestMinusTerm.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/structure/AnalyzeUnjustifiedTest.java

Fix facts in justification, add early arithmetics evaluation

---

src/main/java/at/ac/tuwien/kr/alpha/grounder/transformation/CardinalityNormalization.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/transformation/SumNormalization.java

Add aggregate id to correct list in normalizations.

---

config/checkstyle/checkstyle.xml

Gradle builds were failing with JDK 11, cf. https://github.com/gradle/gradle/issues/8286#issuecomment-456940831

Fix checkstyle config issue occurring with JDK 11

---

src/main/java/at/ac/tuwien/kr/alpha/solver/heuristics/HeapOfActiveAtoms.java

Addresses https://github.com/alpha-asp/Alpha/issues/181#issuecomment-482563854

Fix initialization of heuristic scores

---

src/main/java/at/ac/tuwien/kr/alpha/config/CommandLineParser.java
src/main/java/at/ac/tuwien/kr/alpha/config/SystemConfig.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/CompletionConfiguration.java
src/main/java/at/ac/tuwien/kr/alpha/solver/DefaultSolver.java
src/test/java/at/ac/tuwien/kr/alpha/config/CommandLineParserTest.java
src/test/java/at/ac/tuwien/kr/alpha/solver/AbstractSolverTests.java

We introduce `CompletionConfiguration`, a class that collects configuration parameters for the generation of completion nogoods and justifications. All parameters are configurable from CLI.
Don´t hesitate to change names of classes and fields if desired.

Make completion and justifications configurable from CLI.

---

src/main/java/at/ac/tuwien/kr/alpha/grounder/parser/ParseTreeVisitor.java
src/test/java/at/ac/tuwien/kr/alpha/antlr/ParserTest.java
src/test/resources/escaped_quotes.asp

Remove escaping backslash from escaped quotes ("\\"") in quoted strings

Escaped quotes

---

src/main/java/at/ac/tuwien/kr/alpha/grounder/IndexedInstanceStorage.java

- IndexedInstanceStorage joins instances based on most selective
attribute.

Improve grounder selectivity.

---

src/main/java/at/ac/tuwien/kr/alpha/solver/NoGoodStoreAlphaRoaming.java

Count nogoods only if they are really added.

---

src/main/java/at/ac/tuwien/kr/alpha/solver/NoGoodStoreAlphaRoaming.java
src/main/java/at/ac/tuwien/kr/alpha/solver/learning/GroundConflictNoGoodLearner.java

- GroundConflictNoGoodLearner applies local clause minimization when
analyzing conflicts.

Add learned clause minimization.

---

src/main/java/at/ac/tuwien/kr/alpha/solver/TrailAssignment.java

Make TrailAssignment#replayCounter a long to avoid overflows

---

AUTHORS
CONTRIBUTORS

Updated authors and contributors since Richard is affiliated to both Siemens AG Österreich and to Alpen-Adria-Universität Klagenfurt.

updated authors and contributors

---

src/main/java/at/ac/tuwien/kr/alpha/common/atoms/ExternalAtom.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/atoms/IntervalAtom.java
src/main/java/at/ac/tuwien/kr/alpha/grounder/transformation/ArithmeticTermsRewriting.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/instantiation/LiteralInstantiationStrategyTest.java
src/test/java/at/ac/tuwien/kr/alpha/grounder/transformation/ProgramTransformationTest.java
src/test/resources/transform-test/interval-comparison_atom.in
src/test/resources/transform-test/interval-comparison_atom.out
src/test/resources/transform-test/interval-external_atom.in
src/test/resources/transform-test/interval-external_atom.out

Closes #277 
**Note**: merge PR #279 before this one, changes from #279 contained here

Support ExternalAtoms in IntervalTermRewriting (Issue #277)

---

alpha-cli-app/build.gradle.kts

cli: Upgrade Log4j

---

README.md

I've recently gotten around to get started on my "side-side-"project of writing a beginner-friendly guide on ASP and have been publishing my results via github pages [here](https://madmike200590.github.io/asp-guide/). The guide is still very much a work in progress and is going to grow significantly, both in terms of quantity as well as quality, but I think the tutorial as it is now might already be useful.
I'd like to reference the guide from Alpha's `README.md` in order to give people an easily digestible starting point for learning ASP.

Link to "A coder's guide to answer set programming" from README.md

---

alpha-cli-app/src/main/resources/simplelogger.properties
alpha-cli-app/src/test/resources/simplelogger.properties
alpha-commons/src/test/resources/simplelogger.properties
alpha-core/src/test/resources/simplelogger.properties
alpha-solver/src/test/resources/simplelogger.properties

Fix SimpleLogger time format

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
gradlew

Upgrade Gradle to 7.6
